### ISSUE TITLE
[Enhancement idea] Add comment

### ISSUE THREAD

**Issue by nicolas-raoul** [Questetra/qbpms-client-swagger#3]
The Questetra web GUI allows a user to add comments.
It would be cool if we could add comments via Swagger too. It is already possible for [stars](https://online-demo-en.questetra.net/s/swagger/index.html?urls.primaryName=Workflow%20API&oauth2RedirectUrl=https%3A%2F%2Fonline-demo-en.questetra.net%2Fs%2Fswagger%2Foauth2-redirect.html&validatorUrl=#/Workitem/addStar).
Actually, is there an underlying REST API for comments?
Thank you!

**Comment by hatanaka-akihiro** [comment]
Does "comment" mean "Open Chat"?

Open Chat REST API is not public yet.

However you can build something original Open Chat REST API using Message Start Event (HTTP) and Service Task.

https://support.questetra.com/addons/openchat-postjointextdata/?_ga=2.268485873.1089468171.1534125226-2095135142.1493025732

Regards

**Comment by nicolas-raoul** [comment]
I am actually talking about this kind of comment to a process:
![screenshot from 2018-08-14 18-32-22](https://user-images.githubusercontent.com/99590/44084029-97695c14-9ff0-11e8-89fd-e56d9e57300e.png)

The REST API seems to have this feature, even though I am not sure what integer I should enter in `data[?]`: https://gist.github.com/yehara/1246898#file-messagestartclient-java-L45

**Comment by hatanaka-akihiro** [comment]
"?" in "data[?]" is number of data.

You can check parameters from property dialog of Message Start Event (HTTP).

"URL / Parameter details" button.

Regards.

**Comment by nicolas-raoul** [comment]
Unfortunately, with this technique the comment does not appear at the same place as if I had typed it into the Web GUI:
![screenshot_2018-08-15 - questetra bpm suite](https://user-images.githubusercontent.com/99590/44128822-f38ad718-a07f-11e8-97ea-2f7d96621a2d.png)

**Comment by nicolas-raoul** [comment]
But don't worry, it is OK like this for me :-)

**Comment by hatanaka-akihiro** [comment]
Yes.

"関連する会話 / Conversation abount this" in detail page is one view of "Open Chat" (Enterprise SNS).
So this part is not part of Workflow Application.
Discussion type data item in workflow application is different with "Open Chat".

Regards.
